### PR TITLE
Add admin api to delete topic forcefully

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation

adding admin-api to delete topic forcefully.

### CODE REVIEW

**Comment by merlimat** [comment]
@rdhabalia there are a couple of minor conflicts with the change I merged yesterday on consolidating persistent/non-persistent into `pulsar-admin topics`

**Comment by sijie** [comment]
@merlimat : @rdhabalia has addressed the conflicts. can you review this PR?

**Comment by merlimat** [comment]
@rdhabalia Last week I pushed changes to have `pulsar-admin topics` subcommand. Can you add the `--force` flag (maybe even with `-f` alias) to `CmdTopics` as well?

**Comment by merlimat** [comment]
retest this please

**Comment by merlimat** [comment]
retest this please

**Pull request merged**
