### PR TITLE
fixing/improving logging for function instance

### PR DESCRIPTION
**Pull request by jerrypeng**
### Motivation
logging for java function instance (process mode and localrun) is not working well.  Log files are created at inappropriate locations for logs not captured by the routing appender, functions bookkeeper logs are missing because we are not using the shaded classpath.

The best for logging is just to put all the logs from the java instance log in a single log and not worry about the routing which is only useful when running in threaded mode

### CODE REVIEW

**Comment by sijie** [comment]
retest this please

**Comment by srkukarni** [comment]
run java8 tests

**Comment by srkukarni** [comment]
run integration tests

**Comment by srkukarni** [comment]
@jerrypeng some tests are broken due to this change that needs fixing

**Comment by srkukarni** [comment]
run java8 tests

**Pull request merged**
