### PR TITLE
Add namespace policy for max clients

### PR DESCRIPTION
**Pull request by yush1ga**
### Motivation
We added settings for broker-level max clients limitation in https://github.com/apache/incubator-pulsar/pull/1234
We want to add namespace-level limitation.

### Modifications

- Add NamespacePolicy
- Add Java/REST/CLI API

### Result
We can limit number of client's connections for each topic.

### CODE REVIEW

**Comment by merlimat** [comment]
I think that the max-producers/consumers per topic makes a lot of sense as a broker setting, since it protects it, but I don't see much value in having a namespace level override for this. 

If having unlimited producers on a topic is bad for the broker, we shouldn't allow a tenant to override the setting and allow it.

**Comment by nkurihar** [comment]
@merlimat 
> If having unlimited producers on a topic is bad for the broker, we shouldn't allow a tenant to override the setting and allow it.

I agree it.

Then, how about restricting this command to only superUser like DispatchRate?
https://github.com/apache/incubator-pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java#L587

**Comment by yush1ga** [comment]
In our case, a tenant made a bug that consumers are increase infinitely.
I think namespace level setting is useful for a tenant to detect the behavior they don't expect.

**Comment by merlimat** [comment]
> Then, how about restricting this command to only superUser like DispatchRate? 

For dispatch rate, there are many cases in which you might want to set this to a lower value than the broker defined value (which by default is unlimited). 
I think that even there, if a broker-wide setting is provided, we shouldn't be able to set it lower than the broker setting.

> In our case, a tenant made a bug that consumers are increase infinitely.
> I think namespace level setting is useful for a tenant to detect the behavior they don't expect.

Wouldn't the broker level setting protect in this case as well?

**Comment by nkurihar** [comment]
We consider the following situation:
* Default: limit the number of max clients (e.g. 100)
* For namespaces where topics are 'huge': relax the number of max clients (e.g. 1000) by administrater (not tenant)

Shouldn't we do so?

**Comment by merlimat** [comment]
Sure, it would be great to restrict to administrator only then.

**Comment by yush1ga** [comment]
@merlimat @nkurihar 
I added `validateSuperUserAccess()` to each set method.

**Pull request merged**
