### PR TITLE
[functions] Refactor JavaInstanceRunnable

### PR DESCRIPTION
**Pull request by sijie**
*Motivation*

EffectivelyOnce processing made `JavaInstanceRunnable` very complicated. There are tons of braching logic. It makes code hard to maintain.

*Solution*

Abstract the processing guarantee related logic into a `MessageProcessor` interface. Implement `at-most-once`, `at-least-once` and `effectively-once` processors.

*Result*

After this change, `JavaInstanceRunnable` is much cleaner. `At-Least-Once` and `At-Most-Once` logic are much simpler and easier to debug.

### CODE REVIEW

**Comment by sijie** [comment]
@srkukarni @jerrypeng

**Comment by sijie** [comment]
retest this please

**Comment by srkukarni** [comment]
retest this please

**Comment by srkukarni** [comment]
retest this please

**Comment by srkukarni** [comment]
retest this please

**Comment by srkukarni** [comment]
retest this please

**Comment by jerrypeng** [comment]
retest this please

**Comment by sijie** [comment]
retest this please

**Pull request merged**
