### PR TITLE
Refactored to reflect changes in BK for OrderedExecutor

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Recently merged improvements in BookKeeper OrderedExecutor (see https://github.com/apache/bookkeeper/pull/1309 ). We need to update Pulsar code with the refactored names.

### CODE REVIEW

**Comment by merlimat** [comment]
retest this please

**Comment by jai1** [comment]
retest this please

**Comment by merlimat** [comment]
> I guess we will always run into these issues as long as we keep pointing to SNAPSHOT jar.
> Maybe we should eventually stop using BK SNAPSHOT jar.

Yes, once we're sure BK 4.7 is ready and has all the pieces we need for Pulsar, a release will be made and we'll switch to that release. That should happen soon. 

There were a lot of thing that we had to adjust on both Pulsar and BK side to make the transition to 4.7, it wasn't just possible to make these changes in a branch and sync with master.

**Comment by merlimat** [comment]
> can we add timestamp snapshot version for BK.

We can, though I don't think it needs to be part of this PR

**Pull request merged**
