### PR TITLE
Make sure nextTuple emits tuple with non-null values

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation

Right now, PulsarSpout consumes messages  from the queue, converts into Tuple and emits to the topology. However, if the converted tuple is null then PulsarSpout doesn't emit the tuple when `nextTuple()` is triggered in the topology. It seems if `nextTuple()` doesn't emit the tuple then [Storm-spout](https://github.com/apache/storm/blob/master/storm-client/src/jvm/org/apache/storm/trident/spout/RichSpoutBatchExecutor.java#L108) doesn't batch the tuples and it creates penalty for PulsarSpout. 
Recently, we have seen that one of the  client-app that uses `PulsarSpout` returns null for for most of the messages while converting pulsar-message to tuple (`getMessageToValuesMapper()`) to throw away pulsar-messages. Because of this behavior `nextTuple()` doesn't emit messages for most of the messages and it decreases overall spout processing significantly.

### Modifications

- make sure `nextTuple()` always emits non-null tuple by skipping messages which generates null tuple.

### Result

- it should improve spout processing throughput in usecase where client-app returns null tuple for a pulsar-message.

### CODE REVIEW

**Comment by rdhabalia** [comment]
@revans2 can you also please take a look if this make sense.

**Comment by rdhabalia** [comment]
retest this please

**Comment by revans2** [comment]
I am not sure this is the best solution.  You are using recursion to try and fix a problem that should be simple to do in an iterative way.

Why not have mapToValueAndEmit just return a boolean saying did I emit something or not, and then loop until something is emitted.
For Example
```
             if (LOG.isDebugEnabled()) {
                 LOG.debug("[{}] Receiving the next message from pulsar consumer to emit to the collector", spoutId);
             }
             try {
                 boolean done=false;
                 while (!done) {
                     msg = consumer.receive(1, TimeUnit.SECONDS);
                     if (msg != null) {
                         ++messagesReceived;
                         messageSizeReceived += msg.getData().length;
                         done = mapToValueAndEmit(msg);
                     } else {
                        //There was nothing queued to emit so don't try again right now.
                        done = true;
                     }
                }
             } catch (PulsarClientException e) {
                 LOG.error("[{}] Error receiving message from pulsar consumer", spoutId, e);
             }
```

**Comment by rdhabalia** [comment]
@revans2 updated the changes.

**Comment by rdhabalia** [comment]
@merlimat can you also please take a look of this.

**Comment by jerrypeng** [comment]
@merlimat Sorry for not looking at this earlier, but it look good to me

**Pull request merged**
