### PR TITLE
Added pulsar-1.22.0-incubating to site configuration

### PR DESCRIPTION
**Pull request by jai1**

### CODE REVIEW

**Comment by merlimat** [comment]
Will merge once the mirrors are updated. Once this gets merged the site will start pointing downloads to 1.22 release.

**Comment by merlimat** [comment]
retest this please

**Comment by merlimat** [comment]
retest this please

**Comment by merlimat** [comment]
retest this please

**Comment by merlimat** [comment]
@jai1 please rebase from master

**Comment by merlimat** [comment]
retest this please

**Comment by jai1** [comment]
retest this please

**Comment by merlimat** [comment]
retest this please

**Comment by merlimat** [comment]
retest this please

**Pull request merged**
