### PR TITLE
TopicPatterns are now supported by python functions

### PR DESCRIPTION
**Pull request by srkukarni**
### Motivation

Explain here the context, and why you're making that change.
What is the problem you're trying to solve.

### Modifications

Describe the modifications you've done.

### Result

After your change, what will change.

### CODE REVIEW

**Comment by pouledodue** [comment]
🐍 👍

**Comment by srkukarni** [comment]
run integration tests

**Comment by srkukarni** [comment]
run integration tests

**Comment by srkukarni** [comment]
run integration tests

**Comment by srkukarni** [comment]
run java8 tests

**Comment by srkukarni** [comment]
run java8 tests

**Comment by srkukarni** [comment]
@sijie I believe there are already tests to test the pattern based consumer. Thus not sure if a new one is needed for this.

**Pull request merged**
