### PR TITLE
Removed internal shading

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Remove all dependency shading across internal modules

### Modifications

 * Use Protobuf-3.4.0 to match same version as BK
 * Upgraded to ZK 3.5.4 to match same version as BK

### Result
 
 * Smaller bin.tgz distribution file 
 * Easier development in IDEs

### CODE REVIEW

**Comment by srkukarni** [comment]
retest this please

**Comment by sijie** [comment]
retest this please

**Comment by srkukarni** [comment]
retest this please

**Comment by mgodave** [comment]
retest this please

**Comment by srkukarni** [comment]
retest this please

**Comment by sijie** [comment]
Nice finding at zookeeper server! @merlimat

**Pull request merged**
