### PR TITLE
 [website] Enable Translation & Localization

### PR DESCRIPTION
**Pull request by sijie**
*Motivation*

Docusaurus allows for easy translation functionality using [Crowdin](https://crowdin.com/).
Documentation files written in English are uploaded to Crowdin for translation by users within a community.

*Changes*

- Enable the integration with Crowdin.
- Adjust hyperlinks to include `language`.

Crowdin project: https://crowdin.com/project/apache-pulsar

### CODE REVIEW

**Comment by sijie** [comment]
for reviewers, this change is based on #2247 . so gitsha 6d08fa3 is the change to be reviewed in this PR.

**Comment by sijie** [comment]
@cckellogg ^^

**Comment by jiazhai** [comment]
👍

**Comment by sijie** [comment]
> Can we have a statement that says translated documents will be licensed under AL2 on the project description or somewhere?

We don't store the translated the md files directly. However we store the generated html files in asf-site branch. 

It is a good idea to put a statement in the site2 README explaining all the translated documents will be licensed under AL2.

> And we also need to make sure that only committers have a privilege to approve suggested translations.

yes. I will add committers as managers to that crowdin project once this is live on the website.

**Comment by sijie** [comment]
@maskit I add a section called "contribute translations" in the README.md. Add a statement there saying all the translations are licensed under ALv2

**Comment by sijie** [comment]
rerun java8 tests

**Comment by maskit** [comment]
@sijie The added section looks perfect, but I was worried about a case people suggest translations without reading those contribution guide, because there’s no references on Crowdin side. Maybe I’m too anxious but there should be no cons to have a reference for the README or a statement on Crowdin side.

**Comment by sijie** [comment]
@maskit : I updated the https://crowdin.com/project/apache-pulsar to have a statement all contributed translations are licensed under Apache License V2. I also add you as the manager, so you can edit that project as well.

**Comment by sijie** [comment]
@maskit can you review this again once you have time?

**Pull request merged**
