### PR TITLE
CPP Client - Reducing number of duplicate lookups

### PR DESCRIPTION
**Pull request by jai1**
### Motivation
(A) During a graceful shutdown, the broker sends CLOSE_PRODUCER / CLOSE_CONSUMER command to the client, which triggers the reconnection logic.
(B) After the connection is closed the ClientConnection.close() also triggers the reconnection logic for all registered consumers/producers.
If (A) doesn't complete before (B) then lookups and CREATE_PRODUCER / CREATE_CONSUMER commands are sent twice - this is not a functional issue because the broker returns success for the duplicate command but this leads a twice the required number of lookups.

### Modifications

Put all operation on the producers and consumers map (in ClientConnection) inside a lock.
Remove the consumer/producer from producers/consumers map if CLOSE_PRODUCER / CLOSE_CONSUMER command is received.

### Result

No functional change, lesser lookups.

### CODE REVIEW

**Comment by rdhabalia** [comment]
I think build is failing because it stuck in one of the cpp-test: https://api.travis-ci.org/jobs/251351136/log.txt?deansi=true

**Comment by merlimat** [comment]
@jai1 Build is still failing : 

```
main: /usr/include/boost/smart_ptr/shared_ptr.hpp:653: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = boost::asio::basic_deadline_timer<boost::posix_time::ptime>; typename boost::detail::sp_member_access<T>::type = boost::asio::basic_deadline_timer<boost::posix_time::ptime>*]: Assertion `px != 0' failed.
[63/73] BasicEndToEndTest.testResendViaSendCallback returned/aborted with exit code -6 (4402 ms)
```

**Comment by merlimat** [comment]
@jai1 the test did pass this time but it seems there's some race condition with this change that triggers to access the shared_prt after it was destroyed.

**Comment by jai1** [comment]
@merlimat - Yes we need to fix "BasicEndToEndTest.testResendViaSendCallback"
I will look into it later this week because I am not able to reproduce the bug in my test environment.

**Pull request merged**
