### PR TITLE
Add pulsar python client osx vagrant templates

### PR DESCRIPTION
**Pull request by aahmed-se**
These are files to generate python 2 and python 3 osx pulsar client packages via vagrant virtual machines

### CODE REVIEW

**Comment by aahmed-se** [comment]
Done

**Comment by merlimat** [comment]
@aahmed-se I had one comment above as well: 

> Instead of dev/pulsar-client-osx, I think these should go under pulsar-client-cpp/python/pkg or similar

**Comment by aahmed-se** [comment]
done

**Comment by merlimat** [comment]
@aahmed-se 

```
2018-06-06\T\00:37:49.338 [WARNING] Missing header in: /home/jenkins/jenkins-slave/workspace/pulsar_precommit_java8/pulsar-client-cpp/python/pkg/osx/osx-10.13-python3.6/generate-wheel-file.sh
```

Make sure all files have ASF headers. You can use `mvn license:format`

**Comment by aahmed-se** [comment]
Done

**Comment by aahmed-se** [comment]
done

**Comment by merlimat** [comment]
retest this please

**Pull request merged**
