### PR TITLE
Make broker configurable to own non-persistent namespace

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation

As discussed at #451 : In cluster we may need a way to isolate few of the brokers which only own non-persistent topics or we want to configure broker which doesn't own non-persistent topics (by default broker can own both kinds of topics). So, load-manager should have a way to identify namespace which has non-persistent characteristics and based on broker mode it assigns non-persistent bundles to appropriate brokers.
- Therefore, namespace should be configured such a way that only non-persistent topics can be assigned under it.
- Broker can be configured to  not own non-persistent topics
- Broker can be configured to only own non-persistent topics

### Modifications

- namespace can be configured with non-persistency
- broker can be configured to not own non-persistent topic 
- broker can be configured to only own non-persistent topics 

### Result

We can isolate few of the brokers which can only serve non-persistent topics in case if we don't want to serve both kind of topics in the same broker.

Note: 
- this PR is based on #452  I will rebase this PR once we rebase #452 
- I will document non-peristent topic once we are fine with both the PRs.

### CODE REVIEW

**Comment by merlimat** [comment]
What is the main intent of having the configuration switch to enable/disable persistent/non-persistent topics on a broker? Is is to protect the brokers while the non-persistent mode is being tested out and reaches maturity? 

Couldn't this be also achieved with isolation policies?

**Comment by rdhabalia** [comment]
> Is it to protect the brokers while the non-persistent mode is being tested out and reaches maturity?

yes, it helps us to start using this feature and we can use this switch to avoid impact of unknown issues for persistent topics until this feature is matured.

> Couldn't this be also achieved with isolation policies?

yes, it can be achieved but based on team discussion if broker starts with only non-persistent mode then admin doesn't have to run behind for even non-persistent namespace and load-manager automatically takes care assignment of bundles.

**Comment by merlimat** [comment]
> yes, it can be achieved but based on team discussion if broker starts with only non-persistent mode then admin doesn't have to run behind for even non-persistent namespace and load-manager automatically takes care assignment of bundles.

Sounds good. Is the plan to keep the switch temporarely or indefinitely?

Also, as discussed in the mailing list, can you start drafting a wiki page to recollect all the design points to support non persistent topics?

**Comment by rdhabalia** [comment]
> Also, as discussed in the mailing list, can you start drafting a wiki page to recollect all the design points to support non persistent topics?

Sure, I will draft it based on design agreement we had on #438 #452  and this PR.

**Comment by rdhabalia** [comment]
> Is the plan to keep the switch temporarely or indefinitely?

I think we can remove it once this feature gets matured and broker can handle non-persistent topic tradeoff which won't impact ongoing persistent topic performance.

**Comment by rdhabalia** [comment]
Created a new PR #538 so, closing this one.

**Pull request closed without merging**
