### PR TITLE
Add documentation and flexible aws-credential plugin to support aws-role

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation

Right now, KinesisSink's credentialProvider-plugin doesn't support session-token which can be used in case user access stream with IAM-role instead IAM-user.

### Modifications

- Made KinesisSink's credentialProvider plugin more generic which can be used by both IAM user and roles.
- Add documentation for KinesisSink usage.
- Add test cases for Kinesis Sink.

### Result

- KinesisSink can be used for IAM roles as well.

### CODE REVIEW

**Comment by rdhabalia** [comment]
retest this please

**Comment by rdhabalia** [comment]
retest this please

**Comment by rdhabalia** [comment]
retest this please

**Comment by merlimat** [comment]
retest this please

**Pull request merged**
