### PR TITLE
[schema] add schemas for primtive types

### PR DESCRIPTION
**Pull request by sijie**

### CODE REVIEW

**Comment by sijie** [comment]
retest this please

**Comment by sijie** [comment]
run java8 tests
run integration tests

**Comment by sijie** [comment]
retest this please

**Comment by sijie** [comment]
retest this please

**Comment by sijie** [comment]
run java8 tests
run integration tests

**Comment by sijie** [comment]
run java8 tests 
run integration tests

**Comment by srkukarni** [comment]
run java8 tests
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Pull request merged**
