### PR TITLE
Fixed apache rat errors

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

There are several missing ASF header missing in new files added since last release.

### CODE REVIEW

**Comment by jai1** [comment]
I had to add some more excludes in pom.xml to get pass the rat check 

https://github.com/jai1/pulsar/tree/ratFixes

```
+            <exclude>site/*</exclude>
+            <exclude>site/*/*</exclude>
+            <exclude>site/*/*/*</exclude>
+            <exclude>site/*/*/*/*</exclude>
+            <exclude>.github/*</exclude>
+            <exclude>build/docker/protobuf.patch</exclude>
```

**Comment by merlimat** [comment]
@jai1 these directories are not included in the src package

**Comment by jai1** [comment]
ok - how do you run the apache-rat check?

I just ran "mvn apache-rat:check" on the root directory and got these files as error

**Comment by merlimat** [comment]
> I just ran "mvn apache-rat:check" on the root directory and got these files as error 

What "counts" for the release is what we distribute in term of the tgz with the sources rather than the git repo.

**Pull request merged**
