### PR TITLE
Package name changes

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Renamed Java package names and references from `com.yahoo.pulsar` to `org.apache.pulsar`

### CODE REVIEW

**Comment by rdhabalia** [comment]
1. `pulsar-broker/src/test/resources/log4j.properties:log4j.logger.com.yahoo.pulsar=OFF`

2. SCM change: 
```
pom.xml:    <developerConnection>scm:git:ssh://git@github.com:yahoo/pulsar.git</developerConnection>
```

**Comment by merlimat** [comment]
(pushed with rebase to preserve individual commits)

**Comment by rdhabalia** [comment]
it seems last few commits of this PR were not squashed ?

**Comment by merlimat** [comment]
@rdhabalia I did not squashed them on purpose, to separate the commits with just the renaming and the commits with string changes.. So they depend on each other but better to keep them in individual commits for clarity

**Comment by rdhabalia** [comment]
I see.. Sure.

**Pull request closed without merging**
