### PR TITLE
Use log4j2 as slf4j binding for tests

### PR DESCRIPTION
**Pull request by sijie**
### Motivation

in pulsar-functions, we are using log4j2 routing appender for logging. so pulsar-functions is using log4j2, if we are using `slf4j-simple` in the tests, it will cause all the bindings conflict. so the change is propose to move tests to use log4j2 slf4j binding, instead of `slf4j-simple`

### Modifications

- replace `slf4j-simple` with log4j2 bindings in tests
- to avoid copying the log4j2 property files to every modules, we make a default log4j2 property file in buildtools module, and make buildtools module as a default test dependency for every modules.

### Result

- use log4j2 binding for tests

### CODE REVIEW

**Comment by merlimat** [comment]
Since `buildtools` is not using `pulsar` as parent pom, now we have issue with the missing plugins: 

```
[ERROR] Could not find goal 'check' in plugin org.codehaus.mojo:license-maven-plugin:1.14 among available goals add-third-party, aggregate-add-third-party, aggregate-download-licenses, aggregate-third-party-report, check-file-header, comment-style-list, download-licenses, help, license-list, remove-file-header, third-party-report, update-file-header, update-project-license -> 
```

**Comment by sijie** [comment]
@merlimat hmm will take a look

**Comment by sijie** [comment]
@merlimat for now I need checkplugin in buildtools module. in future, if there are more plugins need to be shared between root pom and buildtools, we can consider have a common profile to extend. does that sound okay to you?

**Comment by sijie** [comment]
@merlimat the test has been passed.

**Pull request merged**
