### PR TITLE
Fix CID 262329

### PR DESCRIPTION
**Pull request by maskit**
### Motivation

Simply wrong

### Modifications

Throw the exception

### Result

The exception will be escalated correctly

### CODE REVIEW

**Comment by maskit** [comment]
@jai1 This would be a candidate for 1.22.x.

**Comment by maskit** [comment]
Hm, maybe the test case is wrong?

**Comment by merlimat** [comment]
@maskit I would say to not backport it to 1.22 at this point, because we have not seen problems in practice that could be related to this bug.

**Comment by maskit** [comment]
Got it. I'll ping you after I fix the test.

**Comment by merlimat** [comment]
@maskit I think the test is wrong. 

It is testing with some garbage input and trying to skip some fields. But this line: 

```java
        assertTrue(inputStream.skipField(WireFormat.WIRETYPE_START_GROUP));
```

Would assume that we had some previous "fieldId" already, which since we are reading garbage, we didn't have. 

That is as expected, it all depends on the generated code to not trying to read `WIRETYPE_START_GROUP` without reading the field id before.

**Comment by maskit** [comment]
@merlimat Thank you for looking into the detail. I'm happy to fix the tests but please don't wait me and feel free to fix it yourself if this blocks something else. I just haven't been able to take time for this.

**Comment by maskit** [comment]
retest this please

**Comment by maskit** [comment]
Huh, finally it passed CI tests. I had to rebase this two times because the base revisions were unstable.

**Pull request merged**
