### PR TITLE
Refactored usages of deprecated classes

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Removed some of the warning printed during the build.

### CODE REVIEW

**Comment by maskit** [comment]
Sorry, I couldn't have a time to create issues for the warnings during build.

I still see a warning below. Are you going to fix this too on this PR?
```
[WARNING] /Users/masakazu/git/pulsar/pulsar-common/src/main/java/io/netty/buffer/RecyclableSlicedByteBuf.java:[69,37] [deprecation] DuplicatedByteBuf in io.netty.buffer has been deprecated
```

Also, I'm curious why the class is under netty namespace. Is it because of accessibility (package-private)?

**Comment by maskit** [comment]
retest this please

**Comment by merlimat** [comment]
> I still see a warning below. Are you going to fix this too on this PR?

Fixing this is not straightforward. I think the best option is to get rid of `RecyclableSlicedByteBuf` and upgrade to Netty 4.1 which has something very similar to it. (I actually submitted a PR with the first version of it and then it got improved and merged there). 
Anyway, we should use `buffer.retainedSlice()` and `buffer.retainedDuplicate()`
https://netty.io/4.1/api/io/netty/buffer/ByteBuf.html#retainedSlice--

> [WARNING] /Users/masakazu/git/pulsar/pulsar-common/src/main/java/io/netty/buffer/RecyclableSlicedByteBuf.java:[69,37] [deprecation] DuplicatedByteBuf in io.netty.buffer has been deprecated
> Also, I'm curious why the class is under netty namespace. Is it because of accessibility (package-private)?

Yes, the `RecyclableSlicedByteBuf` is kind of a "hack" to force recycling of duplicate buffers and needs to access internal Netty methods which are package protected.

**Comment by maskit** [comment]
> Anyway, we should use buffer.retainedSlice() and buffer.retainedDuplicate()
https://netty.io/4.1/api/io/netty/buffer/ByteBuf.html#retainedSlice--

That doesn't sound like a small change. Let's do it separately.

**Comment by maskit** [comment]
retest this please

**Pull request merged**
