### PR TITLE
Revert "Recycle OpAddEntry when ledger-ops fails (#1415)"

### PR DESCRIPTION
**Pull request by ivankelly**
If the OpAddEntry is recycled before the callback is triggered, the callback is calling into a dead object.

This reverts commit f5ffbbe1ed2b79be1caf4a59688eab006e932ced.

### CODE REVIEW

**Comment by rdhabalia** [comment]
>  the callback is calling into a dead object

It seems, `cb.addFailed(e, ctx)` is being triggered before it recycles `OpAddEntry`. do we use `OpAddEntry` anywhere after recycling it? is it possible to provide stacktrace where you see this behavior?

**Comment by merlimat** [comment]
@rdhabalia I think this is probably what's happening: 

```
18:19:24.743 [BookKeeperClientWorker-OrderedSafeExecutor-0-0:org.apache.bookkeeper.common.util.SafeRunnable@38] ERROR org.apache.bookkeeper.common.util.SafeRunnable - Unexpected throwable caught 
java.lang.NullPointerException: null
	at org.apache.bookkeeper.mledger.impl.OpAddEntry.addComplete(OpAddEntry.java:108) ~[classes/:?]
	at org.apache.bookkeeper.client.AsyncCallback$AddCallback.addCompleteWithLatency(AsyncCallback.java:91) ~[bookkeeper-server-shaded-4.7.0-SNAPSHOT.jar:4.7.0-SNAPSHOT]
	at org.apache.bookkeeper.client.PendingAddOp.submitCallback(PendingAddOp.java:361) ~[bookkeeper-server-shaded-4.7.0-SNAPSHOT.jar:4.7.0-SNAPSHOT]
	at org.apache.bookkeeper.client.LedgerHandle.errorOutPendingAdds(LedgerHandle.java:1531) ~[bookkeeper-server-shaded-4.7.0-SNAPSHOT.jar:4.7.0-SNAPSHOT]
	at org.apache.bookkeeper.client.LedgerHandle$5.safeRun(LedgerHandle.java:508) ~[bookkeeper-server-shaded-4.7.0-SNAPSHOT.jar:4.7.0-SNAPSHOT]
	at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [bookkeeper-server-shaded-4.7.0-SNAPSHOT.jar:4.7.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_152]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.21.Final.jar:4.1.21.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```

See https://builds.apache.org/job/pulsar_precommit_java8/2/testReport/org.apache.bookkeeper.mledger.impl/ManagedLedgerBkTest/managedLedgerClosed/

**Comment by merlimat** [comment]
retest this please

**Comment by merlimat** [comment]
@rdhabalia I verified that test stops failing after removing the recycle.

**Comment by merlimat** [comment]
retest this please

**Pull request merged**
