### PR TITLE
Remove deprecated newConnect methods

### PR DESCRIPTION
**Pull request by mgodave**
The only piece of code using these methods is a test that is testing to make sure a deprecated method still works. If there is something I'm missing please feel free to enlighten me.

### CODE REVIEW

**Comment by merlimat** [comment]
@mgodave , the `AuthMethod` enum was used in Pulsar before we realized that it was a problem to plug in an arbitrary authentication plugin. For that we switched to "string" based identifier well before open-sourcing Pulsar. 

The issue was, and I suspect that still is, that there are applications running older Pulsar client  version. The test was to ensure that this client can still connect to new brokers. In fact, there's a specific check for that enum in `ServerCnx` in order to maintain compatibility.

**Comment by mgodave** [comment]
ok, I could not see any place it was being used other than an old test.
Feel free to close.

**Comment by mgodave** [comment]
ok, duh, it just registered what you are saying... yes, if there are old
clients we would want to make sure this still works.

**Comment by mgodave** [comment]
would it be acceptable to move these methods, which are only being used in
a test, to the test itself. That way it would be out of the main codebase.

**Comment by merlimat** [comment]
> would it be acceptable to move these methods, which are only being used in
a test, to the test itself. That way it would be out of the main codebase.

Yes, for sure, the `@Deprecated` was just a lazy shortcut for that.

**Pull request merged**
