### PR TITLE
Derive source/sink arg-class name from function-class for file-url

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation

When user submits function with file-url, server loads jar and performs validation. In that case, server should also configures source/sink arg type-class if it's not configured in the function details.

### Modification

when user submits function with url using cli, it doesn't pass type-arg classname into the request, so, server will update it by loading jar and function-class name.

### Result

User can successfully submit function jar with file-url.

### CODE REVIEW

**Comment by rdhabalia** [comment]
rerun integration tests

**Comment by rdhabalia** [comment]
rerun cpp tests

**Comment by rdhabalia** [comment]
sure, I will try to add.

**Comment by rdhabalia** [comment]
rerun integration tests

**Comment by rdhabalia** [comment]
rerun cpp tests

**Comment by sijie** [comment]
cherry-pick 752f1b4 in branch-2.1

**Pull request merged**
