### PR TITLE
Pulsar FAQ

### PR DESCRIPTION
**Pull request by XiaoZYang**
### Motivation

Explain here the context, and why you're making that change.
What is the problem you're trying to solve.

### Modifications

add `faq.md`

### Result

see `faq.md`

### CODE REVIEW

**Comment by zhaijack** [comment]
👍

**Comment by merlimat** [comment]
Thanks @XiaoZYang for starting this!

For the FAQs I was wondering whether the wiki might be an easier way to maintain it.

There are few pros & cons for Wiki vs Repo: 
 Pros: 
  * It's easier to make quick changes
  * Multiple people can edit different questions independently without conflicts

Cons:
 * Right now, only committers have write access to wiki. We could check with INFRA with respect to this
 * There are no PRs comments

Opinions?

**Comment by sijie** [comment]
@XiaoZYang it seems that you pushed a change with non-faq related changes. can you revert it?

**Comment by sijie** [comment]
@merlimat I would prefer website pages. I think it would make review easier.

**Comment by XiaoZYang** [comment]
@sijie Sorry for the mess, I've reverted it .

**Comment by zhaijack** [comment]
for website, it may have a more wide audience.

**Comment by sijie** [comment]
@lucperkins do you have time on helping with the FAQ content here?

**Comment by XiaoZYang** [comment]
@sijie  
1. Yes, the PR has no related changes to FAQ, so I add a revert to it. So I'm now a little bit confused about it, should I still add a revert yet? 
2. Would you mind explaining what is going to do about **helping with the FAQ content here**? If you mean keep updating FAQ content, I'd like to follow it through.

**Comment by sijie** [comment]
@XiaoZYang any reason why this PR was closed?

> "helping with the FAQ content here" 

I was asking @lucperkins help reviewing this PR

**Comment by lucperkins** [comment]
I think that the language needs some polishing and I'd like to put together a specialized template to present the FAQ. But @sijie, I'd say let's accept the PR for now and I can do that work later.

**Comment by sijie** [comment]
@lucperkins that sounds good to me. 

@merlimat @rdhabalia any objections to accept this PR first? then @lucperkins can work on the FAQ template and polishing the language.

**Comment by sijie** [comment]
ping @merlimat @rdhabalia ?

**Comment by sijie** [comment]
ping @merlimat @rdhabalia ?

**Comment by merlimat** [comment]
Sure, let's merge and then link it on the homepage after the cleanup.

**Pull request merged**
