### PR TITLE
Preserve filename of the original function submission

### PR DESCRIPTION
**Pull request by srkukarni**
### Motivation

When we submit a function, currently we don't note down the original filename that was uploaded from the client. For regular java functions this works fine. For python workers we manage by doing tricks wrt tricks like filename using classnames. However when we add things like wheel support, the filename encodes information that cannot be discarded away.
This pr preserves that filename

### Modifications

Describe the modifications you've done.

### Result

After your change, what will change.

### CODE REVIEW

**Comment by sijie** [comment]
There are two failures related to this PR. please take a look.

```
org.apache.pulsar.functions.worker.rest.api.v2.FunctionApiV2ResourceTest.testRegisterFunctionFileUrlWithValidSinkClass
org.apache.pulsar.functions.worker.rest.api.v2.FunctionApiV2ResourceTest.testUpdateFunctionWithUrl
```

**Comment by srkukarni** [comment]
run java8 tests

**Comment by srkukarni** [comment]
run java8 tests

**Comment by srkukarni** [comment]
run java8 tests

**Comment by srkukarni** [comment]
run java8 tests

**Comment by srkukarni** [comment]
run java8 tests
run integration tests

**Comment by srkukarni** [comment]
run java8 tests
run integration tests

**Comment by srkukarni** [comment]
run java8 tests

**Comment by srkukarni** [comment]
run java8 tests
run integration tests

**Comment by srkukarni** [comment]
run integration tests

**Pull request merged**
