### PR TITLE
Upgrade jersey version to 2.25 and powermock to 1.7.3

### PR DESCRIPTION
**Pull request by sijie**
### Motivation

when developing pulsar-functions for PIP-15, we upgraded a few dependencies

so upgrade dependencies in master to prepare merging functions for PIP-15

### Modifications

upgrade jersey version to 2.26.
upgrade powermock to 1.7.3.
move protobuf version to pulsar-common only, since this allows functions depending on a newer protobuf version.

### Result

jersey version is 2.26.
powermock version is 1.7.3
protobuf version defined in pulsar-common

### CODE REVIEW

**Comment by merlimat** [comment]
There are some failures with Jersey: 

```
Caused by: java.lang.IllegalStateException: InjectionManagerFactory not found.
	at org.glassfish.jersey.internal.inject.Injections.lambda$lookupInjectionManagerFactory$0(Injections.java:98)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:98)
	at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:93)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:282)
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:335)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:178)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:370)

```

**Comment by sijie** [comment]
@merlimat I missed the inject package. I fixed this. also includes some other dependencies changes (updated the PR title and description to reflect that)

**Comment by sijie** [comment]
retest this please

**Comment by sijie** [comment]
retest this please

**Comment by sijie** [comment]
retest this please

**Comment by sijie** [comment]
fixed the test case @merlimat

**Comment by sijie** [comment]
2.26 has a big change of making Jersey core independent of any specific injection framework, which it seems to disallow jackson deserialize json with unknown properties. so this change only bumps to 2.25.

https://jersey.github.io/release-notes/2.26.html

**Pull request merged**
