### PR TITLE
More Pulsar Functions documentation

### PR DESCRIPTION
**Pull request by lucperkins**
@srkukarni This is ready for review.

There's still more work that needs to be done here, but this provides reasonably comprehensive docs for the Java API and for deployment/management of functions. Next step will be subscription types and processing guarantees.

### CODE REVIEW

**Comment by merlimat** [comment]
retest this please

**Comment by lucperkins** [comment]
retest this please

**Comment by lucperkins** [comment]
retest this please

**Comment by lucperkins** [comment]
retest this please

**Comment by srkukarni** [comment]
retest this please

**Pull request merged**
