### PR TITLE
Vendored imports

### PR DESCRIPTION
**Pull request by lucperkins**
This PR adds vendored dependencies for the Pulsar Go client, in keeping with best practices for Go. The vendoring strategy here uses the [dep](https://github.com/golang/dep) tool. I can provide docs for updating dependencies later on.

### CODE REVIEW

**Comment by lucperkins** [comment]
This PR was meant to be targeted to @merlimat's local branch. Closing this PR here.

**Comment by lucperkins** [comment]
Hmmm. I'm not sure if Go vendoring really works with "the Apache way" given the need for license headers. I'll do some digging and see how other projects manage this.

**Comment by sijie** [comment]
@lucperkins can't you just exclude vendor directory from license header checking?

**Comment by merlimat** [comment]
An alternative is to do `go get -d ./...` to fetch all dependencies

**Comment by lucperkins** [comment]
@merlimat True, but in the Go community that's considered sub-standard practice because there are no versions, which means that someone could make a breaking change in one of the linked libraries. Since there's only one external dependency here it's probably not such a big risk. I'm happy to defer that decision to others.

**Comment by sijie** [comment]
I think you can pin a revision or tag (but I can be wrong)

**Comment by merlimat** [comment]
@lucperkins @sijie  I have removed the only one dependency in the latest updates to #1764. We shouldn't need this for now.

**Comment by lucperkins** [comment]
@merlimat 👍

**Pull request closed without merging**
