### PR TITLE
remove unnecessary proto def in FunctionsConfig

### PR DESCRIPTION
**Pull request by jerrypeng**
Remove unnecessary proto def in FunctionsConfig. We don't need to fqfn field in FunctionsConfig

### CODE REVIEW

**Comment by sijie** [comment]
retest this please

**Comment by lucperkins** [comment]
@jerrypeng As far as I can tell this *is* necessary for users to be able to specify FQFN in a function's YAML config, like so:

```yaml
jar: my-jar.jar
className: org.example.functions.MyFunction
inputs:
- persistent://sample/standalone/ns1/in
output: persistent://sample/standalone/ns1/out
fqfn: sample/ns1/my-func
```

**Comment by srkukarni** [comment]
@lucperkins My feeling is that this is should be a command line helper rather than something in the fqn. Thus I would vote it to be removed from protobuf, even if that means that in the config file, we need to specify tenant/namespace/name

**Comment by lucperkins** [comment]
@srkukarni I feel like FQFN should be settable either via the command line *and* via YAML or neither. Inconsistent interfaces will likely sow a lot of unnecessary confusion.

**Comment by srkukarni** [comment]
In that case, I'm now questioning the viability of having this feature. Having tenant/namespace/name AND fqn clearly pollutes/increases the surface area unnecessarily imo. @jerrypeng @sijie do you guys have thoughts on this?

**Comment by jerrypeng** [comment]
I am ok with users specifying functions via fqfn but currently FunctionConfig already has tenant, namespace, and name fields.  Adding another field fqfn would be redundant and create multiple sources of truth which can easily result in bugs later on.

**Comment by lucperkins** [comment]
I think the underlying issue here is that using a Protobuf definition as a source of truth for configuration management is an anti-pattern in itself. At some point we should strongly consider using a more native approach.

**Comment by jerrypeng** [comment]
@lucperkins I have discussed with @sijie @srkukarni, we are going to create another class for functions that is user facing and the FunctionConfig proto will be the internal representation.

**Comment by jerrypeng** [comment]
retest this please

**Comment by jerrypeng** [comment]
retest this please

**Comment by jerrypeng** [comment]
@sijie can we merge this?

**Pull request merged**
