### PR TITLE
Fix License Issue

### PR DESCRIPTION
**Pull request by sijie**
### Motivation

Some libaries are not bundled with server distribution anymore.

 ### Changes

Update the LICENSE.bin.txt to reflect the libraries we have in server distribution.

### CODE REVIEW

**Comment by jiazhai** [comment]
@sijie Seems `src/check-binary-license` reported more not bundled libs. This is only track the server dist ones?

**Comment by sijie** [comment]
this tracks the server dist one. where do you run this? and what is your output?

**Comment by jiazhai** [comment]
@sijie Here is the running and output.
run the command, under pulsar root dir, 
```
sh src/check-binary-license ./distribution/server/target/apache-pulsar-2.2.0-incubating-SNAPSHOT-bin.tar.gz


org.apache.commons-commons-compress-1.15.jar unaccounted for in LICENSE
org.objenesis-objenesis-2.1.jar unaccounted for in LICENSE
org.apache.commons-commons-compress-1.8.1.jar mentioned in LICENSE, but not bundled
org.apache.avro-avro-protobuf-1.8.2.jar mentioned in LICENSE, but not bundled
com.google.flatbuffers-flatbuffers-java-1.9.0.jar mentioned in LICENSE, but not bundled

It looks like there are issues with the LICENSE/NOTICE.
```

**Comment by sijie** [comment]
are you running against latest master? latest master has the problem. my change should be fixing that. did you test my branch @jiazhai ?

**Comment by jiazhai** [comment]
@sijie, Thanks for the work. right, it was on latest master. your branch is good.

**Comment by sijie** [comment]
test this please

**Pull request merged**
