### PR TITLE
PIP-7 Introduce Failure-domain and Anti-affinity-namespace group

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation

As mentioned in [PIP-7](https://github.com/apache/incubator-pulsar/wiki/PIP-7:-Pulsar-Failure-domain-and-Anti-affinity-namespaces), introducing "Pulsar Failure domain" and "Anti-affinity-namespace group".

### Modifications

- Add Failure-Domain, Anti-affinity-namespace group
- Add admin-API 
- will add admin-api doc in separate PR once we merge this PR with all changes.

### CODE REVIEW

**Comment by rdhabalia** [comment]
retest this please

**Comment by rdhabalia** [comment]
retest this please

**Comment by rdhabalia** [comment]
retest this please

**Comment by rdhabalia** [comment]
retest this please

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by rdhabalia** [comment]
retest this please

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by rdhabalia** [comment]
@merlimat ping.

**Comment by jai1** [comment]
retest this please

**Comment by rdhabalia** [comment]
retest this please

**Comment by rdhabalia** [comment]
ping @merlimat when your time permits.

**Comment by rdhabalia** [comment]
@saandrews @merlimat  ping

**Comment by rdhabalia** [comment]
retest this please

**Comment by rdhabalia** [comment]
retest this please

**Comment by rdhabalia** [comment]
retest this please

**Pull request merged**
