### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by srkukarni**
### Motivation

This pr does a couple of minor nits
1. Add a log statement in Sink to make it consistent with the Source.
2. Added AllArgs/NoArgs constructor for some test related objects

### Modifications

Describe the modifications you've done.

### Result

After your change, what will change.

### CODE REVIEW

**Comment by sijie** [comment]
run java8 tests

**Comment by srkukarni** [comment]
run integration tests

**Comment by srkukarni** [comment]
run integration tests

**Comment by srkukarni** [comment]
run integration tests

**Comment by srkukarni** [comment]
run integration tests

**Pull request merged**
