### PR TITLE
Added reader endpoint description to WebSocket.md

### PR DESCRIPTION
**Pull request by hrsakai**
### Motivation

No description about websocket reader endpoint in WebSocket.md.

### Modifications

Added the description to WebSocket.md.

### Result

We can read description about websocket reader endpoint.

fixed https://github.com/apache/incubator-pulsar/issues/738

### CODE REVIEW

**Comment by maskit** [comment]
Please see #738. This change has the same issue.

**Comment by hrsakai** [comment]
@maskit 
I fixed sample codes.
Please check it.

**Comment by hrsakai** [comment]
retest this please

**Comment by maskit** [comment]
@hrsakai It seems fine, but should we use `ws.onmessage = function(packet) {`? Why not `ws.on('message', function(message) {`?

**Comment by hrsakai** [comment]
@maskit 
I confirmed and it seems that we should use `ws.on('message', function(message) {`, so I modified sample code.
please, check again.

**Pull request merged**
