### PR TITLE
If left unspecified, function tenants and namespaces should have the same behavior as topics

### PR DESCRIPTION
**Pull request by srkukarni**
### Motivation

Explain here the context, and why you're making that change.
What is the problem you're trying to solve.

### Modifications

Describe the modifications you've done.

### Result

After your change, what will change.

### CODE REVIEW

**Comment by srkukarni** [comment]
@jerrypeng @sijie

**Comment by jerrypeng** [comment]
@srkukarni can we do this for sources and sinks as well

**Comment by srkukarni** [comment]
Because sources/sinks use the CmdFunctions, it applies to them as well.

**Comment by jerrypeng** [comment]
@srkukarni sources and sinks use CmdSource and CmdSink, respectively. They do not use CmdFunctions.  You will need to add the same logic to those places

**Comment by srkukarni** [comment]
@jerrypeng I've added the same to sources and sinks

**Pull request merged**
