### PR TITLE
Fixed Spelling.

### PR DESCRIPTION
**Pull request by jimmycasey**
### Motivation

Explain here the context, and why you're making that change.
What is the problem you're trying to solve.

### Modifications

Describe the modifications you've done.

### Result

After your change, what will change.

### CODE REVIEW

**Comment by srkukarni** [comment]
retest this please

**Comment by sijie** [comment]
rerun java8 tests

**Comment by srkukarni** [comment]
retest this please

**Comment by merlimat** [comment]
rerun java8 tests

**Pull request merged**
