### PR TITLE
Hide namespace cli commands that are no longer relevant

### PR DESCRIPTION
**Pull request by srkukarni**
### Motivation

Explain here the context, and why you're making that change.
What is the problem you're trying to solve.

### Modifications

Describe the modifications you've done.

### Result

After your change, what will change.

### CODE REVIEW

**Comment by srkukarni** [comment]
@merlimat

**Comment by rdhabalia** [comment]
what is the reason for hiding this command?

**Comment by srkukarni** [comment]
In 2.0 the concept of cluster in a topic name goes away. Plus I believe we(and the rest of the industry) have standardized on the keyword topic. The hiding is to make sure that legacy users still have access to the old way.

**Comment by merlimat** [comment]
> what is the reason for hiding this command?

`pulsar-admin namespaces destinations $MY_NAMESPACE` 
was converted into `pulsar-admin namespaces topics $MY_NAMESPACE`. 

Initially, I used an alias in JCommander, but that doesn't really work (and also leaves `topics(destinations)` in the help text which is confusing.

Documentation will refer only to the preferred way, but old command will still work.

**Pull request merged**
