### PR TITLE
[WIP] Pulsar Functions windowing documentation

### PR DESCRIPTION
**Pull request by lucperkins**

### CODE REVIEW

**Comment by lucperkins** [comment]
@aahmed-se I'm not sure what the status of windowing in Pulsar Functions currently is, so probably best to leave this to Jerry. Fortunately, the existing Heron docs serve as a good source of theoretical material and technical diagrams. Most of the work will need to be on how to use.

**Comment by srkukarni** [comment]
@jerrypeng can you pl review

**Comment by lucperkins** [comment]
@sanjeev @jerrypeng This is not ready for review

**Comment by sijie** [comment]
Close this one since it is not active, and we will be on the new website after 2.1.0 release. so have to redo this work anyway.

**Pull request closed without merging**
