### PR TITLE
Modified functions producer consumers to use new builder based api

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

There are few places that are still using the deprecated APIs
 * Functions related topics
 * CompactorTool
 * WebSocket proxy

Updating these to avoid deprecation warnings in build.

### CODE REVIEW

**Comment by sijie** [comment]
@merlimat can you rebase this?

**Comment by sijie** [comment]
@merlimat - just fyi, I rebased this PR to latest master.

**Comment by sijie** [comment]
I fixed the tests, so it should be good now.

**Comment by merlimat** [comment]
retest this please

**Pull request merged**
