### PR TITLE
Make navbar more mobile friendly

### PR DESCRIPTION
**Pull request by lucperkins**
### Motivation

At the moment, the website's navbar has a variety of UX problems on mobile, including sizing, overflow, and other issues.

### Modifications

I've removed some CSS styling that either wasn't necessary or created a broken experience.

### Result

The navbar will provide an experience more in line with what users will expect. Not perfect but I think a major improvement.

### CODE REVIEW

**Comment by merlimat** [comment]
retest this please

**Comment by merlimat** [comment]
retest this please

**Comment by lucperkins** [comment]
@merlimat I'm getting this (non-website-related) error in CI:

```
[ERROR] Tests run: 542, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,225.036 s <<< FAILURE! - in TestSuite
[ERROR] socketTest(org.apache.pulsar.websocket.proxy.ProxyPublishConsumeTest)  Time elapsed: 0.198 s  <<< FAILURE!
java.lang.AssertionError: null: lists don't have the same size expected [6] but found [10]
	at org.apache.pulsar.websocket.proxy.ProxyPublishConsumeTest.socketTest(ProxyPublishConsumeTest.java:160)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ProxyPublishConsumeTest.socketTest:160 null: lists don't have the same size expected [6] but found [10]
[INFO] 
[ERROR] Tests run: 542, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[ERROR] There are test failures.
```

Should I submit an issue?

**Comment by merlimat** [comment]
> Should I submit an issue?
There's already an issue open for that flaky test, though is not easy to replicate in local env.

**Comment by merlimat** [comment]
retest this please

**Pull request merged**
