### PR TITLE
Use builder methods in getting started docs

### PR DESCRIPTION
**Pull request by ivankelly**
It was previously using deprecated methods.

### CODE REVIEW

**Comment by ivankelly** [comment]
ah, it was an old version of the client. Still confusing for them though.

**Comment by sijie** [comment]
shall put a link on the 2.0 documents to refer back to 1.22.x release doc if people are using 1.22.x clients? just like what we did for 2.0 release before. in this way, it might be better than changing the documentation in 2.0 back. thoughts?

**Comment by ivankelly** [comment]
@sijie @merlimat Another user hit same issue today. Python module is broken for 2.0, and when they roll back to 1.22 the topic name doesn't work.

**Comment by sijie** [comment]
@merlimat what is your take here? shall we merge this first to avoid user confusions? then we can consider a better solution?

**Comment by sijie** [comment]
@ivankelly @merlimat any updates?

**Comment by ivankelly** [comment]
@sijie @merlimat changed it to leave the topic names as they are, and just have the builder changes.

**Pull request merged**
