### PR TITLE
 [tiered storage] Use NAR plugin to package offloaders 

### PR DESCRIPTION
**Pull request by sijie**
### Motivation

Offloader typically involves a new storage system, which usually involves dependencies that
might be conflicting with the dependencies of Pulsar. We want to package offloader implementations
as what we did for connectors, so people can decide which offloader to use and only include it.
People would also become easier to write its offloader if needed.

 ### Changes

- Update `tiered-storage/jcloud` to package it using nifi-nar plugin.
- Add bunch of utils in managed-ledger to locate offloader nar packages and load `LedgerOffloaderFactory` from corresponding NAR package.
- Add a new distribution module to package offloaders into one distribution, as what we did for connectors.
- Update pulsar-all image to include offloaders

 ### NOTES

This change doesn't get rid of jcloud-shaded. because jcloud is using `ServiceLoad` and Guice injection. It makes
things very tricky on class loading. Not attempt to address the problem any time soon. We can pin `jcloud-shaded` version
as what we did for `protobuf-shaded` in next release.

### CODE REVIEW

**Comment by sijie** [comment]
This change is based on #2392 . The gitsha f9c56ba is the change to be reviewed in this PR.

**Comment by sijie** [comment]
Now this PR is ready for review

**Comment by sijie** [comment]
Please don't merge this - I think it breaks some integration tests. still looking into them.

**Comment by sijie** [comment]
the integration tests were broken due to an empty driver name. 419b4784ba50c945a187a2192a4c1745920b95ea is the fix. This change should be ready to go now.

**Comment by sijie** [comment]
@ivankelly @jiazhai please take a look at this PR

**Comment by sijie** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by jiazhai** [comment]
@sijie lgtm. Seems There was an error in integration test.
https://builds.apache.org/job/pulsar_precommit_integrationtests/3319/

**Comment by jiazhai** [comment]
rerun integration tests

**Comment by sijie** [comment]
rerun integration tests

**Comment by sijie** [comment]
rerun integration tests

**Pull request merged**
