### PR TITLE
support subscription-type to be passed in sink-function

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation

Sometimes, user wants to maintain message-ordering while using sink-function. So, sink-cli should  have a param to accept pulsar-source-subscription type.

### Modifications

add param to pass source subscription type in sink-cli.

### Result

User can set subscription type for sink-function.

### CODE REVIEW

**Comment by jerrypeng** [comment]
Can we not just infer from the processing guarantee. If the processing guarantee is set At-least-once or at-most-once, the subscription type for the source should be Shared and for Effectively-once, it would be failover

**Comment by merlimat** [comment]
> f the processing guarantee is set At-least-once or at-most-once, the subscription type for the source should be Shared and for Effectively-once, it would be failover

You might want to retain ordering even for at-least-once mode

**Comment by rdhabalia** [comment]
retest this please

**Comment by rdhabalia** [comment]
@sijie I think we should consider it for 2.1.0 because it will be required if someone wants to use sink with ordering guarantee.

**Comment by sijie** [comment]
@rdhabalia I think we used to have subscription type but we removed it sometime ago. @jerrypeng and @srkukarni have more context.

regarding releases, can we include this as 2.1.1 release, not to delay 2.1.0 release? thoughts @merlimat ?

**Comment by rdhabalia** [comment]
> I think we used to have subscription type but we removed it sometime ago.

umm.. then how can we maintain the ordering without it ?

> regarding releases, can we include this as 2.1.1 release, not to delay 2.1.0 release?

my only concern was that user might not be able to use sink-connector with 2.1.0 if they need message ordering guarantee, else I am fine.

**Comment by merlimat** [comment]
I don't think this should be a blocker for 2.1. We are already very late and left out other fixes, otherwise we keep finding issues or improvements to do and we never actually cut the release :). 

To retain ordering one can always use effectively once mode on the function. 

In general, I would rather have a parameter called "retain ordering " in the function configuration, which might be easier to understand than shaheed/failover

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by rdhabalia** [comment]
> otherwise we keep finding issues or improvements to do and we never actually cut the release :).

alright.

> In general, I would rather have a parameter called "retain ordering " in the function configuration,
 
changed it.

**Pull request merged**
