### PR TITLE
Fix REST APIs provided by Pulsar proxy

### PR DESCRIPTION
**Pull request by massakam**
### Motivation

The following entry points provided by Pulsar proxy does not work properly.
```
/status.html
/admin/*
/lookup/*
```
They always return an 404 error.

### Modifications

~~Added `clusterName` to the proxy configuration in order to acquire a URL for proxying the http requests from configuration store servers.~~

Modified AdminProxyHandler to get the list of active brokers from ZooKeeper and route HTTP request to one of them in round-robin.

If `brokerWebServiceURL` or `brokerWebServiceURLTLS` is specified in proxy.conf, proxy always routes request to that URL.

The value of the existing `brokerServiceURL` can not be used, because it should be a URL that starts with `pulsar://`, not `http://`.

Also, modified WebServer to set the context path when adding proxy servlet.
Otherwise, the requests to `/status.html` are not handled properly by VipStatus.

### Result

Pulsar proxy will be able to handle the http requests to the above entry points successfully.

### CODE REVIEW

**Comment by massakam** [comment]
Uhm... it makes sense.
I will reconsider the way to solve this problem.

**Comment by massakam** [comment]
@merlimat Modified AdminProxyHandler to handle HTTP connection in the same way as Pulsar wire protocol. Would you review again?

**Comment by massakam** [comment]
> Finally, I think we should fix this issue for 2.0.1 patch release, since right now the proxy would fail to start if the broker url is not set in proxy.conf

Changed the milestone to 2.0.1.

**Comment by merlimat** [comment]
Backported to branch-2.0 at afa4e6441d254e49b8957053b725b1de3a14c282

**Pull request merged**
