### PR TITLE
Change HTTP status code which WebSocket proxy returns to producer whe…

### PR DESCRIPTION
**Pull request by massakam**
…n backlog exceeds threshold

### Motivation

Currently, WebSocket proxy returns 500 error to producer that is trying to connect when backlog exceeds the threshold.
However, I think ~~403~~ 503 error is more suitable.

### Modifications

Modify ProducerHandler to return ~~403~~ 503 error if ProducerBlockedQuotaExceededError or ProducerBlockedQuotaExceededException occurs.

### Result

The reason why producer has failed to connect to WebSocket proxy will be easier to understand.

### CODE REVIEW

**Comment by maskit** [comment]
I don't think 403 suits this case because the code is for authentication and authorization, technically. And 4xx errors are basically caused by client side. If server side limitation is the cause, 5xx should be used. 503 would be a best choice. However, if some bad client is requesting too many requests, 429 would be another option.

**Comment by massakam** [comment]
It makes sense. I have changed the status code to 503.

**Comment by massakam** [comment]
retest this please

**Comment by merlimat** [comment]
@massakam One thing that might also help is to include the producer/consumer exception message in the 500 error. That might help to quickly find out what the issue is (on the websocket proxy side) without having to search the proxy logs.

**Comment by massakam** [comment]
retest this please

**Comment by massakam** [comment]
retest this please

**Comment by massakam** [comment]
retest this please

**Pull request merged**
