### PR TITLE
[docker] introduce a pulsar standalone image

### PR DESCRIPTION
**Pull request by sijie**
## Motivation

`pulsar` and `pulsar-all` are designed for running pulsar components on production.
although it can be used for running standalone, people still need to run a separate docker container for pulsar dashboard.

 ## Changes

introduce a `pulsar-standalone` image to package everything into one image. so people can run launch a pulsar standalone in one line command
in docker, including dashboard.

### CODE REVIEW

**Comment by sijie** [comment]
@cckellogg ^^

**Comment by sijie** [comment]
@cckellogg not sure if we can easily change to sqlite. It is probably ok, however I would not suggest changing it right now. Because it requires fair amount of testing.

Yes we should update the dashboard. Will create a task to follow up.

**Comment by kramasamy** [comment]
@sijie @merlimat - these code seems to be copy of the code under /dashboard. This is not a clean way to do this - since any changes in /dashboard - have to be changed here as well. Is there a way to build the docker directly from the files under /dashboard ?

**Comment by sijie** [comment]
We can’t do it, because docker doesn’t allow accessing files outside the dockerfile directory. To deliver this ASAP, we have to copy the files

**Comment by sijie** [comment]
you can point to a location of a dockerfile. But in the dockerfile defintion, you can’t access files not in the same dir as the dockerfile, and you can’t use symlinks as well. That’s why on building pulsar image, we copy the packages to the dockerfile dir.

**Comment by kramasamy** [comment]
Another options is move the dockerfile to the top. Duplicating code and config will be difficult to manage as time goes on

**Comment by sijie** [comment]
Sure. We can reorganize modules to do that. but it will take some time to make sure it doesn’t break others like CI, release process and such. Thats why I didn’t do that for this PR.

**Comment by sijie** [comment]
run java8 tests

**Pull request merged**
