### PR TITLE
Schema registry documentation

### PR DESCRIPTION
**Pull request by lucperkins**

### CODE REVIEW

**Comment by merlimat** [comment]
cc/ @mgodave

**Comment by sijie** [comment]
@lucperkins what is the state of this PR? is it ready for review?

@mgodave can you review this?

**Comment by mgodave** [comment]
On the list for today.

**Comment by lucperkins** [comment]
@sijie @mgodave This is NOT ready for review, and work on this can really only continue when the schema registry is integrated with the clients.

**Comment by lucperkins** [comment]
@mgodave This is ready for review

**Pull request merged**
