### PR TITLE
Publish pulsar-client-admin as a shaded artifact

### LINKED ISSUE #1091: Provide shaded Jar for pulsar-admin
#### Expected behavior

Pulsar-admin is the module that contains the Java interface for the admin API. 

We should distribute a `pulsar-admin` that by default shades all the dependencies, along with `pulsar-admin-original` unshaded, same as for the `pulsar-client` artifact.

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Fixes #1091 

Publish shaded jar for `pulsar-client-admin` to avoid conflicts with other dependencies.

### CODE REVIEW

**Comment by merlimat** [comment]
retest this please

**Comment by sschepens** [comment]
Are se going to provide a non shaded artifact?

**Comment by merlimat** [comment]
@sschepens I followed the same path as the `pulsar-client`: the `pulsar-client-admin-original` will be published unshaded.

**Comment by sschepens** [comment]
:+1:

**Comment by merlimat** [comment]
retest this please

**Pull request merged**
