### PR TITLE
Remove Aerospike Connector

### PR DESCRIPTION
**Pull request by aahmed-se**
Remove Aerospike connector due to license considerations of dependent libraries.

**Motivation**

Aerospike client currently takes a dependency on gnu crypto, which carries a gpl license. This is not compliant with ASF policies as it is not permitted to have any dependencies with GPL+exceptions in Apache projects. 
 
Extended discussion on the issue is here.
https://github.com/aerospike/aerospike-client-java/issues/110

### CODE REVIEW

**Comment by sijie** [comment]
@aahmed-se you need to rebase your branch

**Comment by aahmed-se** [comment]
Rebased on master

**Comment by BrianNichols** [comment]
Aerospike Java client 4.1.11 adds the ability to switch between GNU and Bouncy Castle crypto libraries at compile time. Bouncy Castle has a MIT-based license.

Aerospike Java client 4.1.11 adds the ability to switch between GNU and Bouncy Castle crypto libraries at compile time.  Bouncy Castle has a [MIT-based license](https://www.bouncycastle.org/license.html).

There are now two Aerospike Java client libraries available on [Maven Central Repository](https://search.maven.org/search?q=aerospike-client).  The previously existing **aerospike-client** continues to link with GNU crypto.  The new **aerospike-client-bc** links with Bouncy Castle crypto.

To use AerospikeClient with Bouncy Castle crypto, define this dependency in your pom.xml.

```xml
    <dependency>
      <groupId>com.aerospike</groupId>
      <artifactId>aerospike-client-bc</artifactId>
      <version>4.1.11</version>
    </dependency>
```
Aerospike requests that you restore AerospikeClient support with this new client library.

**Comment by sijie** [comment]
@BrianNichols thank you for pointing this out. we will revert the change and use `aerospike-client-bc`

**Pull request merged**
