### PR TITLE
Cleanup unnecessary casting and creating variables

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation

I think due to recent refactoring some of the minor code which is not necessary to keep. so, cleaning up unnecessary assignments.

### CODE REVIEW

**Comment by rdhabalia** [comment]
retest this please

**Comment by rdhabalia** [comment]
retest this please

**Comment by rdhabalia** [comment]
retest this please

**Comment by jerrypeng** [comment]
retest this please

**Comment by sijie** [comment]
rerun java8 tests

**Pull request merged**
