### PR TITLE
Make twitter source to emit records with schema info

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Have the Twitter source to emit a POJO so that it gets published with schema info on the topic.

### CODE REVIEW

**Comment by merlimat** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by srkukarni** [comment]
run integration tests

**Comment by sijie** [comment]
@merlimat : I think this change fails `TestCmdSources`. so those tests might be needed to update

**Comment by srkukarni** [comment]
closing in favor of https://github.com/apache/incubator-pulsar/pull/2433

**Pull request closed without merging**
