### PR TITLE
Upgrade RocksDb to 5.13.1

### LINKED ISSUE #674: Assertion failure in RocksDB when opening the index db
In some cases, the bookie from the standalone pulsar service is crashing on startup. 

```
2017-08-10 13:03:51,646 - INFO  - [main:Bookie@506] - using ledger storage: org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorage
2017-08-10 13:03:51,711 - INFO  - [main:DbLedgerStorage@132] - Started Db Ledger Storage
2017-08-10 13:03:51,711 - INFO  - [main:DbLedgerStorage@133] -  - Write cache size: 256 MB
2017-08-10 13:03:51,712 - INFO  - [main:DbLedgerStorage@134] -  - Read Cache: 64 MB
2017-08-10 13:03:51,712 - INFO  - [main:DbLedgerStorage@135] -  - Read Ahead Batch size: : 100
Assertion failed: (filter->size() > 0), function GetFilter, file table/block_based_table_reader.cc, line 1133.
Abort trap: 6
```

Once it gets into that state is not recovering.

Stack traces:

```
 thread #6, stop reason = signal SIGSTOP
    frame #0: 0x00007fffd445cd42 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fffd454a457 libsystem_pthread.dylib`pthread_kill + 90
    frame #2: 0x00007fffd43c2420 libsystem_c.dylib`abort + 129
    frame #3: 0x00007fffd4389893 libsystem_c.dylib`__assert_rtn + 320
    frame #4: 0x000000013da81279 librocksdbjni1259198247081385980.jnilib`rocksdb::BlockBasedTable::GetFilter(rocksdb::BlockHandle const&, bool, bool) const + 1017
    frame #5: 0x000000013da7e202 librocksdbjni1259198247081385980.jnilib`rocksdb::BlockBasedTable::Open(rocksdb::ImmutableCFOptions const&, rocksdb::EnvOptions const&, rocksdb::BlockBasedTableOptions const&, rocksdb::InternalKeyComparator const&, std::__1::unique_ptr<rocksdb::RandomAccessFileReader, std::__1::default_delete<rocksdb::RandomAccessFileReader> >&&, unsigned long long, std::__1::unique_ptr<rocksdb::TableReader, std::__1::default_delete<rocksdb::TableReader> >*, bool, bool, int) + 4338
    frame #6: 0x000000013da7958a librocksdbjni1259198247081385980.jnilib`rocksdb::BlockBasedTableFactory::NewTableReader(rocksdb::TableReaderOptions const&, std::__1::unique_ptr<rocksdb::RandomAccessFileReader, std::__1::default_delete<rocksdb::RandomAccessFileReader> >&&, unsigned long long, std::__1::unique_ptr<rocksdb::TableReader, std::__1::default_delete<rocksdb::TableReader> >*, bool) const + 90
    frame #7: 0x000000013d996912 librocksdbjni1259198247081385980.jnilib`rocksdb::TableCache::GetTableReader(rocksdb::EnvOptions const&, rocksdb::InternalKeyComparator const&, rocksdb::FileDescriptor const&, bool, unsigned long, bool, rocksdb::HistogramImpl*, std::__1::unique_ptr<rocksdb::TableReader, std::__1::default_delete<rocksdb::TableReader> >*, bool, int, bool) + 546
    frame #8: 0x000000013d996dfa librocksdbjni1259198247081385980.jnilib`rocksdb::TableCache::FindTable(rocksdb::EnvOptions const&, rocksdb::InternalKeyComparator const&, rocksdb::FileDescriptor const&, rocksdb::Cache::Handle**, bool, bool, rocksdb::HistogramImpl*, bool, int, bool) + 602
    frame #9: 0x000000013d99716a librocksdbjni1259198247081385980.jnilib`rocksdb::TableCache::NewIterator(rocksdb::ReadOptions const&, rocksdb::EnvOptions const&, rocksdb::InternalKeyComparator const&, rocksdb::FileDescriptor const&, rocksdb::RangeDelAggregator*, rocksdb::TableReader**, rocksdb::HistogramImpl*, bool, rocksdb::Arena*, bool, int) + 394
    frame #10: 0x000000013d85b35d librocksdbjni1259198247081385980.jnilib`rocksdb::BuildTable(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, rocksdb::Env*, rocksdb::ImmutableCFOptions const&, rocksdb::MutableCFOptions const&, rocksdb::EnvOptions const&, rocksdb::TableCache*, rocksdb::InternalIterator*, std::__1::unique_ptr<rocksdb::InternalIterator, std::__1::default_delete<rocksdb::InternalIterator> >, rocksdb::FileMetaData*, rocksdb::InternalKeyComparator const&, std::__1::vector<std::__1::unique_ptr<rocksdb::IntTblPropCollectorFactory, std::__1::default_delete<rocksdb::IntTblPropCollectorFactory> >, std::__1::allocator<std::__1::unique_ptr<rocksdb::IntTblPropCollectorFactory, std::__1::default_delete<rocksdb::IntTblPropCollectorFactory> > > > const*, unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<unsigned long long, std::__1::allocator<unsigned long long> >, unsigned long long, rocksdb::CompressionType, rocksdb::CompressionOptions const&, bool, rocksdb::InternalStats*, rocksdb::TableFileCreationReason, rocksdb::EventLogger*, int, rocksdb::Env::IOPriority, rocksdb::TableProperties*, int) + 3981
    frame #11: 0x000000013d912099 librocksdbjni1259198247081385980.jnilib`rocksdb::DBImpl::WriteLevel0TableForRecovery(int, rocksdb::ColumnFamilyData*, rocksdb::MemTable*, rocksdb::VersionEdit*) + 1337
    frame #12: 0x000000013d910563 librocksdbjni1259198247081385980.jnilib`rocksdb::DBImpl::RecoverLogFiles(std::__1::vector<unsigned long long, std::__1::allocator<unsigned long long> > const&, unsigned long long*, bool) + 2355
    frame #13: 0x000000013d90f3ca librocksdbjni1259198247081385980.jnilib`rocksdb::DBImpl::Recover(std::__1::vector<rocksdb::ColumnFamilyDescriptor, std::__1::allocator<rocksdb::ColumnFamilyDescriptor> > const&, bool, bool, bool) + 1370
    frame #14: 0x000000013d91371e librocksdbjni1259198247081385980.jnilib`rocksdb::DB::Open(rocksdb::DBOptions const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<rocksdb::ColumnFamilyDescriptor, std::__1::allocator<rocksdb::ColumnFamilyDescriptor> > const&, std::__1::vector<rocksdb::ColumnFamilyHandle*, std::__1::allocator<rocksdb::ColumnFamilyHandle*> >*, rocksdb::DB**) + 2238
    frame #15: 0x000000013d912c27 librocksdbjni1259198247081385980.jnilib`rocksdb::DB::Open(rocksdb::Options const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, rocksdb::DB**) + 1351
    frame #16: 0x000000013d83610c librocksdbjni1259198247081385980.jnilib`___lldb_unnamed_symbol106$$librocksdbjni1259198247081385980.jnilib + 28
    frame #17: 0x000000013d8302a3 librocksdbjni1259198247081385980.jnilib`rocksdb_open_helper(JNIEnv_*, long, _jstring*, std::__1::function<rocksdb::Status (rocksdb::Options const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, rocksdb::DB**)>) + 147
    frame #18: 0x000000013d8303a9 librocksdbjni1259198247081385980.jnilib`Java_org_rocksdb_RocksDB_open__JLjava_lang_String_2 + 73
```

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

5.13.1 contains a fix for the long outstanding bug with rocksdb deleteRange operation that leaves empty SST and makes it crash on startup with a failed assertion.

Fixes #674 #1049

### CODE REVIEW

**Comment by sijie** [comment]
@merlimat can you also update bk?

**Comment by merlimat** [comment]
> @merlimat can you also update bk?

Yes, we should do that for 4.8

**Comment by sijie** [comment]
@merlimat probably also for 4.7.1, it is better to keep the rocksdb version same if possible

**Comment by merlimat** [comment]
> @merlimat probably also for 4.7.1, it is better to keep the rocksdb version same if possible 

In general for RocksDB it shouldn't matter since we are not using any of the newer APIs introduced in latests version. The real concern is that we need to test it extensively with 5.13.1 to verify there are no regression on our usages of RocksDB, and this might be a stretch for 2.0.1 release.

**Pull request merged**
