### PR TITLE
Update default values for a few publisher settings

### PR DESCRIPTION
**Pull request by sijie**
### Motivation

with changes #1387 #1386, we can turn the default publisher behavior into:

- enable batching by default
- default batch flush interval to 1ms : it is a good tradeoff between latency and throughput
- use round-robin message router to leverage batching settings

### Modifications

update the default values for publisher configuration

### Result

default values are updated.

### CODE REVIEW

**Comment by sijie** [comment]
retest this please

**Comment by merlimat** [comment]
This PR also needs to be rebased/merged since it was created when there was a very flaky test.

**Comment by sijie** [comment]
@merlimat - rebased to latest master and updated javadocs

**Comment by merlimat** [comment]
@sijie I think some of the tests might be failing because they are expecting some of the changed defaults.

**Comment by sijie** [comment]
managed ledger closed test failed. seems like a flaky test. rebased to latest master.

**Pull request merged**
