### PR TITLE
Release resources for ZLib inflater/deflater when not used

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

While the ZLib Inflater/Deflater classes from JDK are not "Closable", they do have native resources to free. This is currently happening when the objects are finalized, though it would be better to free the memory as soon as possible.

This is not a big problem now since the instances of inflater/deflater are cached per thread.

### CODE REVIEW

**Comment by sijie** [comment]
retest this please

**Comment by sijie** [comment]
retest this please

**Comment by merlimat** [comment]
retest this please

**Comment by merlimat** [comment]
retest this please

**Pull request merged**
