### PR TITLE
Readd MockBookKeeper to Pulsar

### PR DESCRIPTION
**Pull request by ivankelly**
These mocks were moved out of pulsar to the bookkeeper project a few
months ago. While it is good to have mocks generally available for
bookkeeper, if the mock is not in the pulsar code base and we want to
change the behaviour of the mock for a specific case, we need to wait
for a bookkeeper release cycle to do so. It's better to have the mock
in Pulsar, so we can bend it to our needs.

### CODE REVIEW

**Comment by maskit** [comment]
Do the namespaces have to be "org.apache.bookkeeper.client"? These mocks are now Pulsar's, right?

(Am I the only one who read the subject as MacBookKeeper?)

**Comment by ivankelly** [comment]
@maskit it does need to be in the same package because it's not a clean mock like we would have if just mocking an interface. It relies on some package private members of the classes it is overriding unfortunately. If we can move managed ledger to completely using the new bookkeeper apis, then the mocks can go in whatever package we want.

**Comment by ivankelly** [comment]
rerun integration tests

**Comment by ivankelly** [comment]
@maskit sure, will change it

**Comment by ivankelly** [comment]
rerun java8 tests

**Pull request merged**
