### PR TITLE
Performance consumer end-to-end latency can be negative when running …

### PR DESCRIPTION
**Pull request by merlimat**
…on different machines

### Motivation

We can measure "negative" end-to-end latency times when the consumer is on a different machine, since that is calculated with a timestamp set by producer.

### CODE REVIEW

**Comment by merlimat** [comment]
> Currently if the producer and consumer has a difference in timestamp (average t) then we can just add t and still get E2E latency 

If the clocks are skewed, I don't think there's a reliable way to get the e2e latency

**Comment by merlimat** [comment]
...actually that was the reason why I didn't put the e2e latency initially.

**Comment by jai1** [comment]
> ...actually that was the reason why I didn't put the e2e latency initially.

Exactly, cause in different machine scenario this value will never be accurate (or even in same machine using NTP). So I would recommend leaving the code as it is and just add a disclaimer explaining why E2E latency can't be reliable.

**Comment by merlimat** [comment]
> . So I would recommend leaving the code as it is and just add a disclaimer explaining why E2E latency can't be reliable. 

As it is, it gives exception..

**Pull request merged**
