### PR TITLE
renaming/changing FunctionConfig

### PR DESCRIPTION
**Pull request by jerrypeng**
### Motivation

refactoring functions in preparations for adding connector framework

### Modifications

renaming proto FunctionConfig to FunctionDetails and will use the proto object as the internal representations for functions.

Created a user facing config class called FunctionConfig which will map the new FunctionDetails proto object

### CODE REVIEW

**Comment by jerrypeng** [comment]
@sijie @srkukarni please take a look

**Comment by jerrypeng** [comment]
@srkukarni I have moved FunctionConfig to the utils module as requested

**Comment by srkukarni** [comment]
retest this please

**Comment by sijie** [comment]
@jerrypeng can you address the conflict?

**Comment by jerrypeng** [comment]
@sijie I have rebased

**Pull request merged**
