### PR TITLE
Docker compose files for pulsar

### PR DESCRIPTION
**Pull request by ivankelly**
This patch contains docker compose configuration files to quickly
bring up a pulsar cluster locally.

### CODE REVIEW

**Comment by ivankelly** [comment]
Currently only works with docker images generated with #1131 and #1132 applied.

**Comment by merlimat** [comment]
Even though this is not technically a "prod" deployment, should we have it under the `deployment` folder?

**Comment by ivankelly** [comment]
I put it in docker/ because that was PWD when I started working on it. I've no preference on where it lives.

**Comment by ivankelly** [comment]
@merlimat @aahmed-se I reworked these when checking 2.0 rc3. I think they're ready to merge now.

**Comment by raarts** [comment]
Hi, just so you know, I just tried this docker-compose file, and I got:
```Rons-MBP:tmp raarts$ docker-compose up
Pulling conf-eu (apachepulsar/pulsar-test-latest-version:latest)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling conf-eu (apachepulsar/pulsar-test-latest-version:latest)...
ERROR: pull access denied for apachepulsar/pulsar-test-latest-version, repository does not exist or may require 'docker login'
```

so it may need more tweaking before it can be used by a casual passer-by like me..

**Comment by ivankelly** [comment]
@raarts these compose files are for testing the current master code. We cannot push images for these to dockerhub, as they are not official releases (apache legal reasons). So for now, you have to generate the images yourself from the repo.

**Comment by ivankelly** [comment]
@sijie @merlimat can I get a yea or nah on this?

**Comment by ivankelly** [comment]
@sijie @merlimat can I get a yea or nah on this?

**Comment by ivankelly** [comment]
retest this please // integration test failed before anything even ran

**Pull request merged**
