### PR TITLE
fix behavior of JSONSchema for derived classes

### PR DESCRIPTION
**Pull request by jerrypeng**
### Motivation

Currently declaring a JSONSchema of a certain class and serializing a instance of a derived class does not produce the correct behavior

### CODE REVIEW

**Comment by srkukarni** [comment]
run tests

**Comment by srkukarni** [comment]
run cpp tests
run integration tests
run java8 tests

**Comment by srkukarni** [comment]
run integration tests

**Comment by srkukarni** [comment]
run integration tests

**Comment by jerrypeng** [comment]
rerun integration tests

**Comment by sijie** [comment]
run java8 tests

**Comment by srkukarni** [comment]
run integration tests

**Comment by srkukarni** [comment]
@jerrypeng are some unittests failing because of this change?

**Pull request merged**
