### PR TITLE
fix pkg location init

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation

fix pkg location init while creating function pkg.

### CODE REVIEW

**Comment by rdhabalia** [comment]
retest this please

**Comment by jerrypeng** [comment]
@rdhabalia seems like there is a unit test failure

**Comment by rdhabalia** [comment]
retest this please

**Comment by rdhabalia** [comment]
retest this please

**Comment by srkukarni** [comment]
@rdhabalia looks like the failure of unittest is genuine

**Comment by rdhabalia** [comment]
retest this please

**Comment by rdhabalia** [comment]
retest this please

**Comment by rdhabalia** [comment]
> looks like the failure of unittest is genuine

yes, test-case was giving home dir as a download dir which was not accessible.

**Comment by rdhabalia** [comment]
retest this please

**Comment by rdhabalia** [comment]
retest this please

**Pull request merged**
