### PR TITLE
Add authorization support on function apis

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation

Function admin api should have capability to perform authorization before creating/modifying function using admin-api.

### Modifications

Add support to enable authentication, authorization on admin-api.

### Result

Function api can authorize function request against tenant's admin or super-user.

### CODE REVIEW

**Comment by sijie** [comment]
@rdhabalia FunctionApiV2ResourceTest is failing with NPE

**Comment by rdhabalia** [comment]
retest this please

**Comment by rdhabalia** [comment]
retest this please

**Comment by rdhabalia** [comment]
retest this please

**Comment by sijie** [comment]
merged as 95d4bf7 in branch-2.1

**Pull request merged**
